# Generated by Django 4.2.6 on 2023-11-09 22:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('name',), 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'verbose_name': 'item da Receita', 'verbose_name_plural': 'Itens da Receita'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='measure',
            field=models.CharField(choices=[('unidade', '1 Unidade'), ('xicara', '1 Xícara'), ('fatia', '1 Fatia'), ('prato', '1 Prato'), ('bola', '1 Bola'), ('colher_sopa', '1 Colher de Sopa'), ('colher_cha', '1 Colher de Chá'), ('colher_cafe', '1 Colher de Café')], default='unidade', max_length=20, verbose_name='Medida Caseira'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='portion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Valor da porção (g)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='portions',
            field=models.FloatField(verbose_name='Porções por embalagem'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='value',
            field=models.FloatField(verbose_name='Valor em (g)'),
        ),
    ]
