# Generated by Django 2.2.13 on 2022-08-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('name',), 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'verbose_name': 'item da Receita', 'verbose_name_plural': 'Itens da Receita'},
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor em (g)'),
        ),
    ]
