# Generated by Django 2.2.13 on 2023-10-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_meumodelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='portion',
            field=models.FloatField(verbose_name='Valor da porção (g)'),
        ),
    ]
