# Generated by Django 2.2.13 on 2023-10-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20231010_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='portions',
            field=models.FloatField(verbose_name='Porções por embalagem'),
        ),
    ]
