# Generated by Django 2.2.13 on 2023-10-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20231011_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='value',
            field=models.FloatField(verbose_name='Valor em (g)'),
        ),
    ]
