# Generated by Django 2.2.13 on 2023-10-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20231011_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeuModelo',
        ),
        migrations.AddField(
            model_name='recipe',
            name='measure',
            field=models.CharField(choices=[('unidade', 'Unidade'), ('xicara', 'Xícara'), ('fatia', 'Fatia'), ('prato', 'Prato'), ('colher_sopa', 'Colher de Sopa'), ('colher_cha', 'Colher de Chá'), ('colher_cafe', 'Colher de Café')], default='unidade', max_length=20, verbose_name='Medida Caseira'),
        ),
    ]
