# Generated by Django 2.2.13 on 2023-10-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20231013_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='measure',
            field=models.CharField(choices=[('unidade', 'Unidade'), ('xicara', 'Xícara'), ('fatia', 'Fatia'), ('prato', 'Prato'), ('bola', 'Bola'), ('colher_sopa', 'Colher de Sopa'), ('colher_cha', 'Colher de Chá'), ('colher_cafe', 'Colher de Café')], default='unidade', max_length=20, verbose_name='Medida Caseira'),
        ),
    ]
