# Generated by Django 2.2.13 on 2023-10-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20231013_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='measure',
            field=models.CharField(choices=[('unidade', '1 Unidade'), ('xicara', '1 Xícara'), ('fatia', '1 Fatia'), ('prato', '1 Prato'), ('bola', '1 Bola'), ('colher_sopa', '1 Colher de Sopa'), ('colher_cha', '1 Colher de Chá'), ('colher_cafe', '1 Colher de Café')], default='unidade', max_length=20, verbose_name='Medida Caseira'),
        ),
    ]
