# Generated by Django 2.2.13 on 2022-08-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ingrediente')),
                ('portion', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Porção (g)')),
                ('carboidrato', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Carboidrato (g)')),
                ('acucares_totais', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Açúcares totais (g)')),
                ('acucares_adicionados', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Açúcares adicionados (g)')),
                ('proteina', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Proteína (g)')),
                ('gorduras_totais', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Gorduras Totais (g)')),
                ('gorduras_saturadas', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Gorduras Saturadas (g)')),
                ('gorduras_trans', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Gorduras Trans (g)')),
                ('fibra_alimentar', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fibra Alimentar (g)')),
                ('sodio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sódio (mg)')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
                'db_table': 'ingredient',
            },
        ),
    ]
