# Generated by Django 4.2.6 on 2023-11-09 22:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamina_a',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vitamina A (µg)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='acucares_adicionados',
            field=models.FloatField(verbose_name='Açúcares adicionados (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='acucares_totais',
            field=models.FloatField(verbose_name='Açúcares totais (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carboidrato',
            field=models.FloatField(verbose_name='Carboidrato (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fibra_alimentar',
            field=models.FloatField(verbose_name='Fibra Alimentar (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='gorduras_saturadas',
            field=models.FloatField(verbose_name='Gorduras Saturadas (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='gorduras_totais',
            field=models.FloatField(verbose_name='Gorduras Totais (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='gorduras_trans',
            field=models.FloatField(verbose_name='Gorduras Trans (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='portion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Porção (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteina',
            field=models.FloatField(verbose_name='Proteína (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sodio',
            field=models.FloatField(blank=True, null=True, verbose_name='Sódio (mg)'),
        ),
    ]
