# Generated by Django 2.2.13 on 2023-10-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='acucares_adicionados',
            field=models.FloatField(verbose_name='Açúcares adicionados (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='acucares_totais',
            field=models.FloatField(verbose_name='Açúcares totais (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carboidrato',
            field=models.FloatField(verbose_name='Carboidrato (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fibra_alimentar',
            field=models.FloatField(verbose_name='Fibra Alimentar (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='gorduras_saturadas',
            field=models.FloatField(verbose_name='Gorduras Saturadas (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='gorduras_totais',
            field=models.FloatField(verbose_name='Gorduras Totais (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='gorduras_trans',
            field=models.FloatField(verbose_name='Gorduras Trans (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='portion',
            field=models.FloatField(verbose_name='Porção (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteina',
            field=models.FloatField(verbose_name='Proteína (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sodio',
            field=models.FloatField(verbose_name='Sódio (mg)'),
        ),
    ]
