# Generated by Django 4.2.6 on 2023-11-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_ingredient_user_ingredient_vitamina_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='acucares_adicionados',
            field=models.FloatField(default=0.0, verbose_name='Açúcares adicionados (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='acucares_totais',
            field=models.FloatField(default=0.0, verbose_name='Açúcares totais (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carboidrato',
            field=models.FloatField(default=0.0, verbose_name='Carboidrato (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fibra_alimentar',
            field=models.FloatField(default=0.0, verbose_name='Fibra Alimentar (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='gorduras_saturadas',
            field=models.FloatField(default=0.0, verbose_name='Gorduras Saturadas (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='gorduras_totais',
            field=models.FloatField(default=0.0, verbose_name='Gorduras Totais (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='gorduras_trans',
            field=models.FloatField(default=0.0, verbose_name='Gorduras Trans (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteina',
            field=models.FloatField(default=0.0, verbose_name='Proteína (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sodio',
            field=models.FloatField(default=0.0, verbose_name='Sódio (mg)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamina_a',
            field=models.FloatField(default=0.0, verbose_name='Vitamina A (µg)'),
        ),
    ]
