# Generated by Django 4.2.6 on 2023-11-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0004_ingredient_show_extra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='show_extra_fields',
        ),
    ]
