# Generated by Django 4.2.6 on 2023-11-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0005_remove_ingredient_show_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='acido_folico',
            field=models.FloatField(default=0.0, verbose_name='Ácido Fólico (µg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='acido_omega3',
            field=models.FloatField(default=0.0, verbose_name='Ácido alfa-linolênico Ômega 3 (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='acido_omega6',
            field=models.FloatField(default=0.0, verbose_name='Ácido alfa-linolênico Ômega 6 (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='acido_pantotenico',
            field=models.FloatField(default=0.0, verbose_name='Ácido Pantotênico (µg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='biotina',
            field=models.FloatField(default=0.0, verbose_name='Biotina (µg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calcio',
            field=models.FloatField(default=0.0, verbose_name='Cálcio (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cobre',
            field=models.FloatField(default=0.0, verbose_name='Cobre (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='colesterol',
            field=models.FloatField(default=0.0, verbose_name='Colesterol (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='colina',
            field=models.FloatField(default=0.0, verbose_name='Colina (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cromo',
            field=models.FloatField(default=0.0, verbose_name='Cromo (µg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ferro',
            field=models.FloatField(default=0.0, verbose_name='Ferro(mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fluor',
            field=models.FloatField(default=0.0, verbose_name='Flúor (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fosforo',
            field=models.FloatField(default=0.0, verbose_name='Fósforo (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='gorduras_monoinsaturadas',
            field=models.FloatField(default=0.0, verbose_name='Gorduras monoinsaturadas (g)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='gorduras_omega3',
            field=models.FloatField(default=0.0, verbose_name='Gorduras poli-insaturadas, Ômega 3 (g)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='gorduras_omega6',
            field=models.FloatField(default=0.0, verbose_name='Gorduras poli-insaturadas, Ômega 6 (g)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='iodo',
            field=models.FloatField(default=0.0, verbose_name='Iodo (µg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='magnesio',
            field=models.FloatField(default=0.0, verbose_name='Magnésio (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='manganes',
            field=models.FloatField(default=0.0, verbose_name='Manganês (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='molibdenio',
            field=models.FloatField(default=0.0, verbose_name='Molibdênio (µg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='niacina',
            field=models.FloatField(default=0.0, verbose_name='Niacina (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='potassio',
            field=models.FloatField(default=0.0, verbose_name='Potássio (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='riboflavina',
            field=models.FloatField(default=0.0, verbose_name='Riboflavina (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='selenio',
            field=models.FloatField(default=0.0, verbose_name='Selênio (µg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tiamina',
            field=models.FloatField(default=0.0, verbose_name='Tiamina (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamina_b12',
            field=models.FloatField(default=0.0, verbose_name='Vitamina B12 (µg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamina_b6',
            field=models.FloatField(default=0.0, verbose_name='Vitamina B6 (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamina_b9',
            field=models.FloatField(default=0.0, verbose_name='Vitamina B9 (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamina_c',
            field=models.FloatField(default=0.0, verbose_name='Vitamina C (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamina_d',
            field=models.FloatField(default=0.0, verbose_name='Vitamina D (µg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamina_e',
            field=models.FloatField(default=0.0, verbose_name='Vitamina E (mg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamina_k',
            field=models.FloatField(default=0.0, verbose_name='Vitamina K (µg)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='zinco',
            field=models.FloatField(default=0.0, verbose_name='Zinco (mg)'),
        ),
    ]
